ss: Fix build with old libc headers without AF_VSOCK
At the moment Linux Kernel 3.2 is the last supported LTS. It comes
without AF_VSOCK support (added only in 3.10), therefore old libcs,
such as glibc before 2.18 does not provide, cause ss(8) tool build
failures like following:

  ss.c:294:15: error: 'AF_VSOCK' undeclared here (not in a function)
  ss.c:323:2: error: array index in initializer not of integer type
  ss.c:323:2: error: (near initialization for 'default_afs')
  make[1]: *** [ss.o] Error 1
  make[1]: *** Waiting for unfinished jobs....
  make: *** [all] Error 2

Provide AF_VSOCK and PF_VSOCK defines for compatibility; adjust
AF_MAX and PF_MAX to reflect change.

Tested in Debian 7 (Wheezy) environment with glibc-2.13 and Linux
Kernel 3.2. Still supported config until 31 May 2018 according to
Debian LTS support page.

Signed-off-by: Serhey Popovych <serhe.popovych@gmail.com>